name: inventory-management
services:
  - name: inventory-management
    type: web
    env: php
    git:
      repository: https://github.com/tauhusoya/inventory
      branch: master
    build:
      builder: nixpacks
      env:
        - name: PHP_VERSION
          value: "8.1"
    run:
      command: php artisan serve --host=0.0.0.0 --port=$PORT
      ports:
        - port: 8080
          protocol: http
    env:
      - name: APP_ENV
        value: production
      - name: APP_DEBUG
        value: false
      - name: LOG_CHANNEL
        value: stack
      - name: CACHE_DRIVER
        value: file
      - name: SESSION_DRIVER
        value: file
      - name: SESSION_LIFETIME
        value: "120"
      - name: QUEUE_CONNECTION
        value: sync
      - name: DB_CONNECTION
        value: pgsql
    hooks:
      build: |
        composer install --no-dev --optimize-autoloader
        npm install
        npm run build
        php artisan key:generate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan migrate --force 