services:
  - type: web
    name: inventory-management
    runtime: php
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      npm install
      npm run build
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stack
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: QUEUE_CONNECTION
        value: sync
      - key: PHP_VERSION
        value: 8.1
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: inventory-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: inventory-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: inventory-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: inventory-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: inventory-db
          property: password

databases:
  - name: inventory-db
    databaseName: inventory
    user: inventory_user
    plan: free 