name: Deploy to InfinityFree

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, fileinfo, gd, exif, zip
        coverage: none
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist
      
    - name: Install NPM dependencies
      run: npm ci
      
    - name: Build assets
      run: npm run build
      
    - name: Generate application key
      run: php artisan key:generate --force
      env:
        APP_KEY: ${{ secrets.APP_KEY }}
        
    - name: Cache configuration
      run: php artisan config:cache
      
    - name: Cache routes
      run: php artisan route:cache
      
    - name: Cache views
      run: php artisan view:cache
      
    - name: Create deployment package
      run: |
        # Remove unnecessary files for production
        rm -rf node_modules
        rm -rf .git
        rm -rf .github
        rm -rf tests
        rm -rf storage/logs/*
        rm -rf storage/framework/cache/*
        rm -rf storage/framework/sessions/*
        rm -rf storage/framework/views/*
        
        # Create zip file
        zip -r deployment.zip . -x "*.git*" "node_modules/*" "tests/*" ".github/*"
        
    - name: Deploy to InfinityFree via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.INFINITYFREE_FTP_SERVER }}
        username: ${{ secrets.INFINITYFREE_FTP_USERNAME }}
        password: ${{ secrets.INFINITYFREE_FTP_PASSWORD }}
        server-dir: ${{ secrets.INFINITYFREE_FTP_DIR }}
        local-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          **/.github/**
          **/storage/logs/**
          **/storage/framework/cache/**
          **/storage/framework/sessions/**
          **/storage/framework/views/**
          
    - name: Run post-deployment commands
      run: |
        # Note: These commands would need to be run manually on InfinityFree
        # or through their control panel
        echo "Deployment completed!"
        echo "Remember to:"
        echo "1. Set up your database on InfinityFree"
        echo "2. Update .env file with production settings"
        echo "3. Run: php artisan migrate --force"
        echo "4. Set proper file permissions" 